name: Release

on:
  pull_request:
  #    tags:
  #      - "v*"
  push:
#    tags:
#      - "v*"

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: sync
          - os: windows-latest
            artifact_name: sync.exe
          - os: macos-latest
            artifact_name: sync

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build project
        run: cargo build --release

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/${{ matrix.artifact_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/${{ matrix.artifact_name }}